dist: bionic
sudo: false
cache:
    directories:
        - $HOME/.cache/pip
        - $HOME/.cache/pipenv

language: python
python:
    # First value is default
    - "{{ cookiecutter.python_version }}"

install:
    - pip install pipenv
    - pipenv install --dev --skip-lock

script:
    - pipenv run fulltest

jobs:
    include:
        {%- if cookiecutter.docs == 'y' %}
        - stage: Test
          name: Test docs
          install:
              - pip install pipenv sphinx
              - pipenv install --skip-lock
          script:
              - pipenv run doctest
              - pipenv run build-docs

        {% endif -%}
        - stage: Coverage
          name: —Åodecov
          before_script:
              - pip install codecov
          script:
              - pytest --cov
              - codecov --required
